spring:
  datasource:
    username: root
    password: root
jwt:
  secret: sdkekdnkikdkfxkdhdjhfhuehkdkhdfsjhjhjhdjsfhieuhfjkdhjkhjkshdfjhkj
  expiration: 86400000
openai:
  api:
    key: "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"
    base-url: "https://api.openai.com/v1/assistants"  # Assistants API 엔드포인트
